language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.5

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels bioconda
    # are not specific to using mini
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# reports on conda-forge is not compiled for py3.4 so we install it with pip
install:
   - echo $TRAVIS_PYTHON_VERSION
   - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
   - conda install --yes pytest pytest-cov pytest-xdist pytest-mock pytest-timeout pytest-runner coveralls coverage mock nose
   - pip install jinja2 reports
   - pip install .

# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=gdsctools --cov-report term-missing  -n 4

after_success:
  coveralls
