name: gdsctools_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- numpy
- pandas==0.20.1
- matplotlib
- scipy==0.19.0
- scikit-learn==0.18.1
- statsmodels==0.8.0
- reports
- bioservices
- pip
- easydev>=0.9.34
- pip:
  - ipython
  - jupyter
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

