name: gdsctools_env

channels:
- bioconda

dependencies:
- numpy
- pandas
- matplotlib
- scipy
- scikit-learn
- statsmodels
- pip:
  - matplotlib
  - easydev>=0.9.31
  - bioservices
  - reports
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212
