name: gdsctools_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- numpy
- pandas
- matplotlib
- scipy
- scikit-learn
- statsmodels
- reports
- bioservices
- pip
- easydev>=0.9.34
- pip:
  - ipython
  - jupyter
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

