# configuration file for the regression pipeline (GDSCTools)
#
# Please see gdsctools.readthedocs.io for details
#
#############################################################


# Analysis
regression:
  method: lasso    # lasso, elasticnet or ridge
  kfold: 10        # Used to automatically estimate best alpha parameter
  randomness: 50   # number of model fitting for significance (most of the time is here)
  boxplot_n: 5     # most important features to use in boxplot

# The input data files in the form of an IC50 and genomic features files
#
# See http://gdsctools.readthedocs.io/en/master/data.html for data formats
#
input:
  ic50:
  genomic_features:
  drug_decode: 


# ANOVA
anova:
    report_directory: "analysis"

