name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies conda
      run: |
        conda install -c conda-forge --quiet mamba  python=${{ matrix.python }}
    - name: Install gdstools with pip
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest  pytest-cov pytest-xdist pytest-mock pytest-timeout  pytest-runner
        pytest --cov-report term --cov=gdsctools
    - name: coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
